spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:com/gpmall/user/dal/persistence/*Mapper.xml"
  type-aliases-package: com.gpmall.user.dal.entitys
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
